#!/bin/sh

echo 'If the below commands are not available follow the install log'
echo 'tail -f output.txt'

echo '# Sign into your Azure account' 
echo 'az login'
echo 'export AZURE_SUBSCRIPTION_ID="<SubscriptionId>"'

echo '# Create an Azure Service Principal and paste the output here'
echo 'export AZURE_TENANT_ID="<Tenant>"'
echo 'export AZURE_CLIENT_ID="<AppId>"'
echo 'export AZURE_CLIENT_SECRET="<Password>"'

echo '# Azure cloud settings'
echo '# To use the default public cloud, otherwise set to AzureChinaCloud|AzureGermanCloud|AzureUSGovernmentCloud'
echo 'export AZURE_ENVIRONMENT="AzurePublicCloud"'

echo 'export AZURE_SUBSCRIPTION_ID_B64="$(echo -n "$AZURE_SUBSCRIPTION_ID" | base64 | tr -d '\n')"'
echo 'export AZURE_TENANT_ID_B64="$(echo -n "$AZURE_TENANT_ID" | base64 | tr -d '\n')"'
echo 'export AZURE_CLIENT_ID_B64="$(echo -n "$AZURE_CLIENT_ID" | base64 | tr -d '\n')"'
echo 'export AZURE_CLIENT_SECRET_B64="$(echo -n "$AZURE_CLIENT_SECRET" | base64 | tr -d '\n')"'

echo '# Finally, initialize the management cluster'
echo 'clusterctl init --infrastructure azure'